channels:
        - defaults
        - conda-forge
        - plotly
dependencies:
        - python
        - numpy
        - pandas
        - xarray
        - netcdf4
        - matplotlib
        - scikit-learn
        - scipy
        - statsmodels
        - cmocean
        - basemap
        - basemap-data-hires
        - spyder
        - notebook
        - termcolor
        - imageio
        - ipyleaflet
        - dash
        - plotly
