channels:
        - defaults
        - conda-forge
        - plotly
        - anaconda
dependencies:
        - python
        - numpy
        - pandas
        - xarray
        - netcdf4
        - matplotlib=3.3.1
        - scikit-learn
        - scipy
        - statsmodels
        - cmocean
        - basemap=1.2.1
        - basemap-data-hires
        - spyder
        - notebook
        - termcolor
        - imageio
        - ipyleaflet
        - dash
        - plotly
        - cftime
